### ISSUE TITLE
"Komplete Kontrol A DAW" not appearing in FL Studio 20.7.3

### ISSUE THREAD

**Issue by iansimpson27** [hobyst/flmidi-kompletekontrol#10]
When I extract the zip file into a subfolder of Documents\Image-Line\FL Studio\Settings\Hardware\ and run FL Studio, the script isn't being picked up.  I have tried disconnecting and reconnecting my Komplete Kontrol A61 with no luck.  Not sure if this problem is specific to the newly released 20.7.3.  Unfortunately 20.7.3 came out just yesterday and I can't find 20.7.2 for download anywhere (only the deprecated earlier versions).

**Comment by hobyst** [comment]
This is a really common problem, but it isn't in my side. The `Komplete Kontrol A DAW` MIDI device is the DAW Control Surface port, a virtual MIDI device created by the Native Instruments' driver when a Komplete Kontrol keyboard is detected. If the device doesn't appear, then it is likely to happen due to driver issues. Try uninstalling the Komplete Kontrol software and the driver, reinstall it from Native Access and see if it still happens.
