### ISSUE TITLE
Knobs on S-Series keyboards only work when turned really fast

### ISSUE THREAD

**Issue by dmoutault** [hobyst/flmidi-kompletekontrol#12]
Hi,

Thank you very much for this script it is awesome.

However, I encountered a problem on the mixer part. When I turn a knob to adjust the volume it's not linear at all. I have to turn it a lot for the cursor to start moving. And once it moves, it changes value far too quickly to adjust properly.

I am having this problem on my s49. On the m32 everything work fine.

Thank you in advance for your help

**Comment by hobyst** [comment]
If on one device it works well but on the other doesn't, then it is likely to hardware issue rather than something I can fix on my side.

You can either use a MIDI monitor like [Pocket MIDI](https://www.morson.jp/pocketmidi-webpage/) or [MIDI-OX](http://www.midiox.com/) to see if the knobs on your S49 work properly or revise your MIDI settings on FL Studio since a bad MIDI configuration can lead to performance issues with the script: 
- You only run the script over the `Komplete Kontrol DAW - 1` device and leave `KOMPLETE KONTROL - 1` as a `(generic controller)`, both devices have to be using different MIDI ports inside FL Studio)
- "Send master sync" option cannot be enabled on them

**Comment by dmoutault** [comment]
I am not thinking of a hardware problem because the knobs work fine on native instrument plugins.
I tested the Midi with Midi OX and I have a normal signal which increments correctly.

The m32 and the s49 are never connected at the same time.
I put a different port between the DAW and Komlete Kontrol - 1

Send master sync is disable.

**Comment by hobyst** [comment]
Send a screenshot of your MIDI settings in FL Studio to see if there's anything out of place, as well as a screenshot of `View > Script Output > Komplete Kontrol DAW - 1`.

**Comment by dmoutault** [comment]
Hi,

![capture](https://user-images.githubusercontent.com/11051032/99193466-58d7dd00-2779-11eb-87f5-0ed3c4d6c7e8.png)
![script view](https://user-images.githubusercontent.com/11051032/99193467-59707380-2779-11eb-96cb-b2411e1288c5.PNG)

Thank you in advance for your help

**Comment by hobyst** [comment]
So far, your MIDI setup looks okay for me. The only thing I could do to fix something like this is to allow the end user to adjust the knob intervals to their liking. Some people have said either it was too fast or two slow, so it's something worth doing and relatively simple to do.

**Comment by dmoutault** [comment]
Hello,

It would be great if you could add this feature :)

**Comment by GradeT45** [comment]
Hey,

I'm really thankful for all of this.

Have you already set up a way to adjust the knobs? 

Much thanks.

**Comment by hobyst** [comment]
> Hey,
> 
> I'm really thankful for all of this.
> 
> Have you already set up a way to adjust the knobs?
> 
> Much thanks.

No, not yet.

**Comment by DieserTii** [comment]
I have the same issue. It seems like the knobs are super laggy when it comes to turn volume up or down in the mixer.

**Comment by hobyst** [comment]
Thanks to another S-Series MK2 user I've finally got to know what's going on with this. The knobs on S-Series keyboards are speed-sensitive and send different MIDI messages depending on the speed the knob is turned at. And because I'm using an A-Series keyboard on my end, the script only reacts to what on the S-Series keyboards would be the message the keyboard sends when a knob is turned at its max speed.

So now that I know what it's actually causing all of this, it would only be a matter of changing some code snippets to make the script react to all the messages indifferently of the knob turning speed (linear). However, making use of the speed sensitiveness would take a bit of time to figure out how to implement it.

I'll try to fix this as soon as possible.

**Comment by hobyst** [comment]
Commit 110447e should fix this issue.

You can test this version by cloning the beta branch of the script using:
```bash
git clone -b beta https://github.com/hobyst/flmidi-kompletekontrol.git --recurse-submodules "Native Instruments Komplete Kontrol"
```

**Comment by DieserTii** [comment]
Big sorry, but I have absolutely no idea, what I have to do now, to test it. :-D

**Comment by hobyst** [comment]
> Big sorry, but I have absolutely no idea, what I have to do now, to test it. :-D

Just delete the "Native Instruments Komplete Kontrol" folder from FL Studio MIDI scripts folder and reinstall the script just like you would normally do following the installation guide. When downloading the script, use the Git installation method, and instead of using the `git` command specified by the guide, use this one instead:

```bash
git clone -b beta https://github.com/hobyst/flmidi-kompletekontrol.git --recurse-submodules "Native Instruments Komplete Kontrol"
```

**Comment by DieserTii** [comment]
Okay I got it! And yeah....what can I say...it´s great! Works very well now! Can adjust channel volume accurately now. In my opinion it coul´d react a little slower but actually i can work with it like it is.

Thank you man!

**Comment by hobyst** [comment]
[Version 4](https://github.com/hobyst/flmidi-kompletekontrol/releases/tag/v4) is the first stable version of the script containing the bugfix for this issue. I'll close this issue and follow up with a new one for the speed sensitivity support on S-Series MK2 keyboards.
