### ISSUE TITLE
Impossible to "link to controller"

### ISSUE THREAD

**Issue by purplewindo** [hobyst/flmidi-kompletekontrol#22]
Hello

I'm on KK M32, I have installed your script and it's work well, thank you!

However, the mixer knobs are locked on volume and panning and i can't link DAW knobs to controller.. I would like to be free to link whatever buttons of the DAW i want with any knobs of my M32 (like the basic fl model). Is there a way to do that ? Modify or delete a part of the script/code?

Thank you

**Comment by hobyst** [comment]
The Komplete Kontrol keyboards have three different modes:
- **DAW mode:** This is the mode that my script enables and allows the user to control the mixer, have advanced transport controls beyond what MCU allows and navigate the UI using the 4D encoder.
- **MIDI mode:** This is the "classic" mode where the keyboard behaves as a regular MIDI keyboard with to 32 assignable MIDI knobs (8 physical knobs * 4 knob pages) and a layout that can be modified using the MIDI template editor found in the Komplete Kontrol software.
- **Komplete Kontrol/Maschine mode:** This is the mode the keyboard enters when either the Komplete Kontrol or Maschine software are used.

With my script enabled you still can map the knobs using the "Link to controller" feature in FL Studio and use them to control parameters inside FL Studio or any plugin you load, but you need to do so while in MIDI mode, as DAW mode makes the keyboard behave differently. In order to switch back and forth between modes in the M32 keyboard:
- **DAW mode:** Press the TRACK button
- **MIDI mode:** Hold SHIFT and press the PLUG-IN button
- **Komplete Kontrol mode:** Hold SHIFT and press the TRACK button. The keyboard will allow you to scroll through all the Komplete Kontrol and Maschine instances currently running in your PC using the OLED screen and the 4D encoder of the keyboard.
- **Maschine mode:** Either press the IDEAS button or use the same method described for the Komplete Kontrol mode.

**Comment by hobyst** [comment]
Assuming issue is fixed due to no further discussion.
