### ISSUE TITLE
Can't find Native Instruments Komplete Kontrol (user) script in the fl studio list

### ISSUE THREAD

**Issue by MrIbzm** [hobyst/flmidi-kompletekontrol#25]
That fixed the problem, thanks!

**Comment by hobyst** [comment]
It's impossible for you to be using FL Studio 20 and still get the scripts to show up on the Controller type list because MIDI Scripting support was introduced in FL Studio 20.7. Because of the redesigned browser and Settings tabs I will assume you are using FL Studio 21.0.3 which makes sense since it's the latest stable version.

It seems FL Studio now doesn't add `(user)` to the end of user scripts as it used to. The script is already showing on the Controller type list as `Native Instruments Komplete Kontrol`:

![](https://github.com/hobyst/flmidi-kompletekontrol/assets/48522412/895f2ac4-35af-4c92-be06-e17c3ec57500)

All you should need is to do is leave the `KOMPLETE KONTROL - 1` device without a port assigned to it,  assign the `Native Instruments Komplete Kontrol` script to the `Komplete Kontrol DAW - 1` device and everything should work as expected.
